# Lista de OBMs gerada e mantida manualmente.
# OBM_LIST: lista plana (code, display) – usada para validação
# OBM_GROUPS: lista agrupada para o dropdown com <optgroup>
#
# Última atualização: inclusão de 53 novas unidades após confronto com
# Estrutura_CBMERJ (planilha de referência). Duplicatas detectadas e
# descartadas (unidades que já existiam sob sigla diferente).

OBM_LIST = [
    # ── CBMERJ ────────────────────────────────────────────────────────────
    # Comando-Geral
    ('CBMERJ_GCG',        'CBMERJ – Gabinete do Comando-Geral'),
    ('CBMERJ_CHGCG',      'CBMERJ – Chefia de Gabinete do CG'),
    ('CBMERJ_NUPROEISBM', 'CBMERJ – NUPROEISBM'),
    ('CBMERJ_FUNESBOM',   'CBMERJ – FUNESBOM'),
    ('CBMERJ_CI',         'CBMERJ – CI'),
    ('CBMERJ_GEP',        'CBMERJ – GEP'),
    ('CBMERJ_AJG',        'CBMERJ – AJG'),
    ('CBMERJ_SCP',        'CBMERJ – SCP'),
    ('CBMERJ_CHC',        'CBMERJ – CHC'),
    ('CBMERJ_MH',         'CBMERJ – Museu Histórico'),
    ('CBMERJ_GBMus',      'CBMERJ – GBMus'),
    ('CBMERJ_CHEMG',      'CBMERJ – CHEMG'),
    ('CBMERJ_SUBCHADM',   'CBMERJ – SUBCHADM'),
    ('CBMERJ_SUBCHOP',    'CBMERJ – SUBCHOP'),
    ('CBMERJ_SEMG',       'CBMERJ – Secretaria do EMG'),
    ('CBMERJ_GGPEMG',     'CBMERJ – Gab. de Gestão de Projetos do EMG'),
    ('CBMERJ_ASSPAR',     'CBMERJ – ASSPAR'),
    # Diretorias / Subcomando
    ('CBMERJ_GSCG',       'CBMERJ – Gabinete do Subcomando-Geral'),
    ('CBMERJ_BM/1',       'CBMERJ – BM/1'),
    ('CBMERJ_BM/4',       'CBMERJ – BM/4'),
    ('CBMERJ_BM/5',       'CBMERJ – BM/5'),
    ('CBMERJ_BM/2',       'CBMERJ – BM/2'),
    ('CBMERJ_BM/3',       'CBMERJ – BM/3'),
    ('CBMERJ_BM/6',       'CBMERJ – BM/6'),
    ('CBMERJ_BM/7',       'CBMERJ – BM/7'),
    ('CBMERJ_ASSEMG',     'CBMERJ – ASSEMG'),
    ('CBMERJ_DGCCO',      'CBMERJ – DGCCO'),
    ('CBMERJ_COCB',       'CBMERJ – Centro de Operações CB'),
    ('CBMERJ_COAPH',      'CBMERJ – Centro de Op. Atend. Pré-Hospitalar'),
    ('CBMERJ_DGP',        'CBMERJ – DGP'),
    ('CBMERJ_CPM',        'CBMERJ – CPM'),
    ('CBMERJ_DGST',       'CBMERJ – DGST'),
    ('CBMERJ_DPPT',       'CBMERJ – DPPT'),
    ('CBMERJ_DCST',       'CBMERJ – Diretoria de Controle de Serv. Técnicos'),
    ('CBMERJ_DGAL',       'CBMERJ – DGAL'),
    ('CBMERJ_CSM',        'CBMERJ – CSM'),
    ('CBMERJ_CSM/MMOTO',  'CBMERJ – CSM/MMOTO'),
    ('CBMERJ_CSM/MOP',    'CBMERJ – CSM/MOP'),
    ('CBMERJ_CSM/MTEL',   'CBMERJ – CSM/MTEL'),
    ('CBMERJ_ALGEBOM',    'CBMERJ – ALGEBOM'),
    ('CBMERJ_ALMED',      'CBMERJ – ALMED'),
    ('CBMERJ_ALOD',       'CBMERJ – ALOD'),
    ('CBMERJ_ALSE',       'CBMERJ – ALSE'),
    ('CBMERJ_DGF',        'CBMERJ – DGF'),
    ('CBMERJ_PAGCEN',     'CBMERJ – Pagadoria Central'),
    ('CBMERJ_DGEI',       'CBMERJ – DGEI'),
    ('CBMERJ_ESCBM',      'CBMERJ – ESCBM'),
    ('CBMERJ_ABMDPII',    'CBMERJ – ABMDPII'),
    ('CBMERJ_CFAP',       'CBMERJ – CFAP'),
    ('CBMERJ_CEICS',      'CBMERJ – CEICS'),
    ('CBMERJ_DBM/ESCOLA', 'CBMERJ – DBM/ESCOLA'),
    ('CBMERJ_CEFID',      'CBMERJ – CEFID'),
    ('CBMERJ_CTRM',       'CBMERJ – CTRM'),
    ('CBMERJ_DI',         'CBMERJ – DI'),
    ('CBMERJ_CIEB',       'CBMERJ – CIEB'),
    ('CBMERJ_DGVP',       'CBMERJ – DGVP'),
    ('CBMERJ_DGS',        'CBMERJ – DGS'),
    ('CBMERJ_PMEDQCG',    'CBMERJ – PMED-QCG'),
    ('CBMERJ_PMEDDGEI',   'CBMERJ – PMED-DGEI'),
    ('CBMERJ_PMEDCSM',    'CBMERJ – PMED-CSM'),
    ('CBMERJ_CGSI',       'CBMERJ – CGSI'),
    ('CBMERJ_DGAS',       'CBMERJ – DGAS'),
    ('CBMERJ_DGDP',       'CBMERJ – DGDP'),
    ('CBMERJ_DGPAT',      'CBMERJ – DGPAT'),
    ('CBMERJ_DGEAO',      'CBMERJ – DGEAO'),
    ('CBMERJ_DGSE',       'CBMERJ – DGSE'),
    # Saúde
    ('CBMERJ_HCAP',       'CBMERJ – HCAP'),
    ('CBMERJ_1_POL',      'CBMERJ – 1ª POL'),
    ('CBMERJ_2_POL',      'CBMERJ – 2ª POL'),
    ('CBMERJ_3_POL',      'CBMERJ – 3ª POL'),
    ('CBMERJ_4_POL',      'CBMERJ – 4ª POL'),
    ('CBMERJ_FARB',       'CBMERJ – FARB'),
    ('CBMERJ_1CTQ',       'CBMERJ – 1º CTQ – Campinho'),
    # Odontologia
    ('CBMERJ_DGO',               'CBMERJ – DGO'),
    ('CBMERJ_CEPO',              'CBMERJ – CEPO'),
    ('CBMERJ_CGOM',              'CBMERJ – Centro Gestor de Odontologia Móvel'),
    ('CBMERJ_CGUOD',             'CBMERJ – CGUOD'),
    ('CBMERJ_1_Odontoclnica',    'CBMERJ – 1ª Odontoclínica'),
    ('CBMERJ_2_Odontoclnica',    'CBMERJ – 2ª Odontoclínica'),
    ('CBMERJ_3_Odontoclnica',    'CBMERJ – 3ª Odontoclínica'),
    ('CBMERJ_4_Odontoclnica',    'CBMERJ – 4ª Odontoclínica'),
    ('CBMERJ_5_Odontoclnica',    'CBMERJ – 5ª Odontoclínica'),
    ('CBMERJ_6_Odontoclnica',    'CBMERJ – 6ª Odontoclínica'),
    ('CBMERJ_7_Odontoclnica',    'CBMERJ – 7ª Odontoclínica'),
    ('CBMERJ_8_Odontoclnica',    'CBMERJ – 8ª Odontoclínica'),
    ('CBMERJ_9_Odontoclnica',    'CBMERJ – 9ª Odontoclínica'),
    ('CBMERJ_10_Odontoclnica',   'CBMERJ – 10ª Odontoclínica'),
    ('CBMERJ_11_Odontoclnica',   'CBMERJ – 11ª Odontoclínica'),
    ('CBMERJ_CRODO_MET',  'CBMERJ – Coord. Regional Odonto. Metropolitana'),
    ('CBMERJ_CRODO_SERR', 'CBMERJ – Coord. Regional Odonto. Serrana'),
    ('CBMERJ_CRODO_SUL',  'CBMERJ – Coord. Regional Odonto. Sul'),
    ('CBMERJ_CRODO_NN',   'CBMERJ – Coord. Regional Odonto. Norte-Noroeste'),
    ('CBMERJ_CRODO_LIT',  'CBMERJ – Coord. Regional Odonto. Litorânea'),
    ('CBMERJ_CRODO_CV',   'CBMERJ – Coord. Regional Odonto. Costa Verde'),
    # ── CBMERJ/CBA I ──────────────────────────────────────────────────────
    ('CBMERJ/CBA_I_CBA_I',       'CBMERJ/CBA I – CBA I'),
    ('CBMERJ/CBA_I_GOCG',        'CBMERJ/CBA I – GOCG'),
    ('CBMERJ/CBA_I_DBM_1/GOCG',  'CBMERJ/CBA I – DBM 1/GOCG'),
    ('CBMERJ/CBA_I_PABM_1/GOCG', 'CBMERJ/CBA I – PABM 1/GOCG'),
    ('CBMERJ/CBA_I_1_GBM',       'CBMERJ/CBA I – 1º GBM'),
    ('CBMERJ/CBA_I_DBM_1/1',     'CBMERJ/CBA I – DBM 1/1'),
    ('CBMERJ/CBA_I_2_GBM',       'CBMERJ/CBA I – 2º GBM'),
    ('CBMERJ/CBA_I_DBM_1/2',     'CBMERJ/CBA I – DBM 1/2'),
    ('CBMERJ/CBA_I_8_GBM',       'CBMERJ/CBA I – 8º GBM'),
    ('CBMERJ/CBA_I_11_GBM',      'CBMERJ/CBA I – 11º GBM'),
    ('CBMERJ/CBA_I_DBM_1/11',    'CBMERJ/CBA I – DBM 1/11'),
    ('CBMERJ/CBA_I_DBM_2/11',    'CBMERJ/CBA I – DBM 2/11'),
    ('CBMERJ/CBA_I_DBM_3/11',    'CBMERJ/CBA I – DBM 3/11'),
    ('CBMERJ/CBA_I_12_GBM',      'CBMERJ/CBA I – 12º GBM'),
    ('CBMERJ/CBA_I_13_GBM',      'CBMERJ/CBA I – 13º GBM'),
    ('CBMERJ/CBA_I_DBM_1/13',    'CBMERJ/CBA I – DBM 1/13'),
    ('CBMERJ/CBA_I_DBM_2/13',    'CBMERJ/CBA I – DBM 2/13'),
    ('CBMERJ/CBA_I_17_GBM',      'CBMERJ/CBA I – 17º GBM'),
    ('CBMERJ/CBA_I_19_GBM',      'CBMERJ/CBA I – 19º GBM'),
    ('CBMERJ/CBA_I_DBM_1/19',    'CBMERJ/CBA I – DBM 1/19'),
    ('CBMERJ/CBA_I_24_GBM',      'CBMERJ/CBA I – 24º GBM'),
    ('CBMERJ/CBA_I_DBM_1/24',    'CBMERJ/CBA I – DBM 1/24'),
    ('CBMERJ/CBA_I_DBM_2/24',    'CBMERJ/CBA I – DBM 2/24'),
    ('CBMERJ/CBA_I_DBM_3/24',    'CBMERJ/CBA I – DBM 3/24'),
    ('CBMERJ/CBA_I_25_GBM',      'CBMERJ/CBA I – 25º GBM'),
    ('CBMERJ/CBA_I_28_GBM',      'CBMERJ/CBA I – 28º GBM'),
    ('CBMERJ/CBA_I_30_GBM',      'CBMERJ/CBA I – 30º GBM'),
    # ── CBMERJ/CBA II ─────────────────────────────────────────────────────
    ('CBMERJ/CBA_II_CBA_II',    'CBMERJ/CBA II – CBA II'),
    ('CBMERJ/CBA_II_6_GBM',     'CBMERJ/CBA II – 6º GBM'),
    ('CBMERJ/CBA_II_DBM_1/6',   'CBMERJ/CBA II – DBM 1/6'),
    ('CBMERJ/CBA_II_DBM_2/6',   'CBMERJ/CBA II – DBM 2/6'),
    ('CBMERJ/CBA_II_DBM_3/6',   'CBMERJ/CBA II – DBM 3/6'),
    ('CBMERJ/CBA_II_DBM_4/6',   'CBMERJ/CBA II – DBM 4/6'),
    ('CBMERJ/CBA_II_PABM_1/6',  'CBMERJ/CBA II – PABM 1/6'),
    ('CBMERJ/CBA_II_15_GBM',    'CBMERJ/CBA II – 15º GBM'),
    ('CBMERJ/CBA_II_DBM_1/15',  'CBMERJ/CBA II – DBM 1/15'),
    ('CBMERJ/CBA_II_DBM_2/15',  'CBMERJ/CBA II – DBM 2/15'),
    ('CBMERJ/CBA_II_DBM_3/15',  'CBMERJ/CBA II – DBM 3/15'),
    ('CBMERJ/CBA_II_16_GBM',    'CBMERJ/CBA II – 16º GBM'),
    ('CBMERJ/CBA_II_DBM_1/16',  'CBMERJ/CBA II – DBM 1/16'),
    ('CBMERJ/CBA_II_DBM_2/16',  'CBMERJ/CBA II – DBM 2/16'),
    # ── CBMERJ/CBA III ────────────────────────────────────────────────────
    ('CBMERJ/CBA_III_CBA_III',   'CBMERJ/CBA III – CBA III'),
    ('CBMERJ/CBA_III_7_GBM',     'CBMERJ/CBA III – 7º GBM'),
    ('CBMERJ/CBA_III_22_GBM',    'CBMERJ/CBA III – 22º GBM'),
    ('CBMERJ/CBA_III_DBM_1/22',  'CBMERJ/CBA III – DBM 1/22'),
    ('CBMERJ/CBA_III_DBM_2/22',  'CBMERJ/CBA III – DBM 2/22'),
    ('CBMERJ/CBA_III_DBM_3/22',  'CBMERJ/CBA III – DBM 3/22'),
    ('CBMERJ/CBA_III_23_GBM',    'CBMERJ/CBA III – 23º GBM'),
    ('CBMERJ/CBA_III_DBM_1/23',  'CBMERJ/CBA III – DBM 1/23'),
    ('CBMERJ/CBA_III_29_GBM',    'CBMERJ/CBA III – 29º GBM'),
    ('CBMERJ/CBA_III_DBM_1/29',  'CBMERJ/CBA III – DBM 1/29'),
    ('CBMERJ/CBA_III_DBM_2/29',  'CBMERJ/CBA III – DBM 2/29'),
    ('CBMERJ/CBA_III_DBM_3/29',  'CBMERJ/CBA III – DBM 3/29'),
    ('CBMERJ/CBA_III_DBM_4/29',  'CBMERJ/CBA III – DBM 4/29'),
    # ── CBMERJ/CBA IV ─────────────────────────────────────────────────────
    ('CBMERJ/CBA_IV_CBA_IV',    'CBMERJ/CBA IV – CBA IV'),
    ('CBMERJ/CBA_IV_CRM/MMOTO', 'CBMERJ/CBA IV – CRM/MMOTO'),
    ('CBMERJ/CBA_IV_5_GBM',     'CBMERJ/CBA IV – 5º GBM'),
    ('CBMERJ/CBA_IV_DBM_1/5',   'CBMERJ/CBA IV – DBM 1/5'),
    ('CBMERJ/CBA_IV_DBM_2/5',   'CBMERJ/CBA IV – DBM 2/5'),
    ('CBMERJ/CBA_IV_DBM_3/5',   'CBMERJ/CBA IV – DBM 3/5'),
    ('CBMERJ/CBA_IV_DBM_4/5',   'CBMERJ/CBA IV – DBM 4/5'),
    ('CBMERJ/CBA_IV_DBM_5/5',   'CBMERJ/CBA IV – DBM 5/5'),
    ('CBMERJ/CBA_IV_DBM_6/5',   'CBMERJ/CBA IV – DBM 6/5'),
    ('CBMERJ/CBA_IV_21_GBM',    'CBMERJ/CBA IV – 21º GBM'),
    ('CBMERJ/CBA_IV_DBM_1/21',  'CBMERJ/CBA IV – DBM 1/21'),
    ('CBMERJ/CBA_IV_DBM_2/21',  'CBMERJ/CBA IV – DBM 2/21'),
    ('CBMERJ/CBA_IV_DBM_3/21',  'CBMERJ/CBA IV – DBM 3/21'),
    ('CBMERJ/CBA_IV_DBM_4/21',  'CBMERJ/CBA IV – DBM 4/21'),
    ('CBMERJ/CBA_IV_DBM_5/21',  'CBMERJ/CBA IV – DBM 5/21'),
    ('CBMERJ/CBA_IV_DBM_6/21',  'CBMERJ/CBA IV – DBM 6/21'),
    # ── CBMERJ/CBA V ──────────────────────────────────────────────────────
    ('CBMERJ/CBA_V_CBA_V',     'CBMERJ/CBA V – CBA V'),
    ('CBMERJ/CBA_V_9_GBM',     'CBMERJ/CBA V – 9º GBM'),
    ('CBMERJ/CBA_V_DBM_1/9',   'CBMERJ/CBA V – DBM 1/9'),
    ('CBMERJ/CBA_V_DBM_2/9',   'CBMERJ/CBA V – DBM 2/9'),
    ('CBMERJ/CBA_V_PABM_1/9',  'CBMERJ/CBA V – PABM 1/9'),
    ('CBMERJ/CBA_V_18_GBM',    'CBMERJ/CBA V – 18º GBM'),
    ('CBMERJ/CBA_V_DBM_1/18',  'CBMERJ/CBA V – DBM 1/18'),
    ('CBMERJ/CBA_V_DBM_2/18',  'CBMERJ/CBA V – DBM 2/18'),
    ('CBMERJ/CBA_V_PABM_1/18', 'CBMERJ/CBA V – PABM 1/18'),
    ('CBMERJ/CBA_V_27_GBM',    'CBMERJ/CBA V – 27º GBM'),
    ('CBMERJ/CBA_V_DBM_1/27',  'CBMERJ/CBA V – DBM 1/27'),
    ('CBMERJ/CBA_V_DBM_2/27',  'CBMERJ/CBA V – DBM 2/27'),
    # ── CBMERJ/CBA VI ─────────────────────────────────────────────────────
    ('CBMERJ/CBA_VI_CBA_VI',   'CBMERJ/CBA VI – CBA VI'),
    ('CBMERJ/CBA_VI_4_GBM',    'CBMERJ/CBA VI – 4º GBM'),
    ('CBMERJ/CBA_VI_DBM_1/4',  'CBMERJ/CBA VI – DBM 1/4'),
    ('CBMERJ/CBA_VI_DBM_2/4',  'CBMERJ/CBA VI – DBM 2/4'),
    ('CBMERJ/CBA_VI_DBM_3/4',  'CBMERJ/CBA VI – DBM 3/4'),
    ('CBMERJ/CBA_VI_DBM_4/4',  'CBMERJ/CBA VI – DBM 4/4'),
    ('CBMERJ/CBA_VI_14_GBM',   'CBMERJ/CBA VI – 14º GBM'),
    ('CBMERJ/CBA_VI_DBM_1/14', 'CBMERJ/CBA VI – DBM 1/14'),
    # ── CBMERJ/CBA VII ────────────────────────────────────────────────────
    ('CBMERJ/CBA_VII_CBA_VII',   'CBMERJ/CBA VII – CBA VII'),
    ('CBMERJ/CBA_VII_10_GBM',    'CBMERJ/CBA VII – 10º GBM'),
    ('CBMERJ/CBA_VII_DBM_1/10',  'CBMERJ/CBA VII – DBM 1/10'),
    ('CBMERJ/CBA_VII_DBM_2/10',  'CBMERJ/CBA VII – DBM 2/10'),
    ('CBMERJ/CBA_VII_DBM_3/10',  'CBMERJ/CBA VII – DBM 3/10'),
    ('CBMERJ/CBA_VII_DBM_4/10',  'CBMERJ/CBA VII – DBM 4/10'),
    ('CBMERJ/CBA_VII_26_GBM',    'CBMERJ/CBA VII – 26º GBM'),
    ('CBMERJ/CBA_VII_DBM_1/26',  'CBMERJ/CBA VII – DBM 1/26'),
    # ── CBMERJ/CBA VIII ───────────────────────────────────────────────────
    ('CBMERJ/CBA_VIII_CBA_VIII',  'CBMERJ/CBA VIII – CBA VIII'),
    ('CBMERJ/CBA_VIII_GBS',       'CBMERJ/CBA VIII – GBS'),
    ('CBMERJ/CBA_VIII_DBM_1/GBS', 'CBMERJ/CBA VIII – DBM 1/GBS'),
    ('CBMERJ/CBA_VIII_PABM_1/GBS','CBMERJ/CBA VIII – PABM 1/GBS'),
    ('CBMERJ/CBA_VIII_1_GSFMA',   'CBMERJ/CBA VIII – 1º GSFMA'),
    ('CBMERJ/CBA_VIII_2_GSFMA',   'CBMERJ/CBA VIII – 2º GSFMA'),
    ('CBMERJ/CBA_VIII_GTSAI',     'CBMERJ/CBA VIII – GTSAI'),
    ('CBMERJ/CBA_VIII_GOA',       'CBMERJ/CBA VIII – GOA'),
    ('CBMERJ/CBA_VIII_DBM_1/GOA', 'CBMERJ/CBA VIII – DBM 1/GOA'),
    ('CBMERJ/CBA_VIII_COVANT',    'CBMERJ/CBA VIII – COVANT'),
    ('CBMERJ/CBA_VIII_GOPP',      'CBMERJ/CBA VIII – GOPP'),
    ('CBMERJ/CBA_VIII_DBM/MOTO',  'CBMERJ/CBA VIII – DBM/MOTO'),
    ('CBMERJ/CBA_VIII_GBRESC',    'CBMERJ/CBA VIII – GBRESC'),
    ('CBMERJ/CBA_VIII_GSE',       'CBMERJ/CBA VIII – Gp. de Socorro de Emergência'),
    # ── CBMERJ/CBA IX ─────────────────────────────────────────────────────
    ('CBMERJ/CBA_IX_CBA_IX',    'CBMERJ/CBA IX – CBA IX'),
    ('CBMERJ/CBA_IX_3_GBM',     'CBMERJ/CBA IX – 3º GBM'),
    ('CBMERJ/CBA_IX_DBM_1/3',   'CBMERJ/CBA IX – DBM 1/3'),
    ('CBMERJ/CBA_IX_DBM_2/3',   'CBMERJ/CBA IX – DBM 2/3'),
    ('CBMERJ/CBA_IX_20_GBM',    'CBMERJ/CBA IX – 20º GBM'),
    ('CBMERJ/CBA_IX_DBM_1/20',  'CBMERJ/CBA IX – DBM 1/20'),
    ('CBMERJ/CBA_IX_DBM_2/20',  'CBMERJ/CBA IX – DBM 2/20'),
    ('CBMERJ/CBA_IX_DBM_3/20',  'CBMERJ/CBA IX – DBM 3/20'),
    # ── CBMERJ/CBA X ──────────────────────────────────────────────────────
    ('CBMERJ/CBA_X_CBA_X',   'CBMERJ/CBA X – CBA X'),
    ('CBMERJ/CBA_X_CER',     'CBMERJ/CBA X – CER'),
    ('CBMERJ/CBA_X_1_GMAR',  'CBMERJ/CBA X – 1º GMAR'),
    ('CBMERJ/CBA_X_DBM_1/M', 'CBMERJ/CBA X – DBM 1/M'),
    ('CBMERJ/CBA_X_DBM_2/M', 'CBMERJ/CBA X – DBM 2/M'),
    ('CBMERJ/CBA_X_2_GMAR',  'CBMERJ/CBA X – 2º GMAR'),
    ('CBMERJ/CBA_X_DBM_3/M', 'CBMERJ/CBA X – DBM 3/M'),
    ('CBMERJ/CBA_X_DBM_4/M', 'CBMERJ/CBA X – DBM 4/M'),
    ('CBMERJ/CBA_X_DBM_5/M', 'CBMERJ/CBA X – DBM 5/M'),
    ('CBMERJ/CBA_X_3_GMAR',  'CBMERJ/CBA X – 3º GMAR'),
    ('CBMERJ/CBA_X_4_GMAR',  'CBMERJ/CBA X – 4º GMAR'),
    ('CBMERJ/CBA_X_DBM_6/M', 'CBMERJ/CBA X – DBM 6/M'),
    # ── SEDEC ─────────────────────────────────────────────────────────────
    ('SEDEC_GABSEC',              'SEDEC – Gabinete do Secretário'),
    ('SEDEC_CH_GAB_SEDEC',        'SEDEC – CH GAB SEDEC'),
    ('SEDEC_ASESP',               'SEDEC – Assessoria Especial'),
    ('SEDEC_ASSEJUR',             'SEDEC – ASSEJUR'),
    ('SEDEC_ASSPLO',              'SEDEC – ASSPLO'),
    ('SEDEC_ACS',                 'SEDEC – ACS'),
    ('SEDEC_ARINT',               'SEDEC – Assessoria de Relações Internacionais'),
    ('SEDEC_ARINST',              'SEDEC – ARINST'),
    ('SEDEC_ARGOV',               'SEDEC – Assessoria de Relações Governamentais'),
    ('SEDEC_CPARJ',               'SEDEC – Coord. Parlamentar no RJ'),
    ('SEDEC_CPABSB',              'SEDEC – Coord. Parlamentar em Brasília'),
    ('SEDEC_CAL',                 'SEDEC – Coord. de Assuntos Legislativos'),
    ('SEDEC_CONTROLADORIA_SEDEC', 'SEDEC – CONTROLADORIA SEDEC'),
    ('SEDEC_CORREGEDORIA',        'SEDEC – Corregedoria-Geral'),
    ('SEDEC_CRD',                 'SEDEC – CRD'),
    ('SEDEC_SUBSEDEC',            'SEDEC – SUBSEDEC'),
    ('SEDEC_SUBGAD',              'SEDEC – Subsecretaria de Gestão Administrativa'),
    ('SEDEC_CRVD_SALA_LILAS',     'SEDEC – CRVD (SALA LILAS)'),
    ('SEDEC_SUAD',                'SEDEC – SUAD'),
    ('SEDEC_DGAF',                'SEDEC – DGAF'),
    ('SEDEC_DGTI',                'SEDEC – DG de Tecnologia da Informação'),
    ('SEDEC_DGBP',                'SEDEC – DG de Bens Patrimoniais'),
    ('SEDEC_DPSEDEC',             'SEDEC – Diretoria de Patrimônio da SEDEC'),
    ('SEDEC_DPCBMERJ',            'SEDEC – Diretoria de Patrimônio do CBMERJ'),
    ('SEDEC_DGI',                 'SEDEC – DG de Intendência'),
    ('SEDEC_CTAPL',               'SEDEC – Centro de Apoio Logístico'),
    ('SEDEC_SUSAU',               'SEDEC – SUSAU'),
    ('SEDEC_CTTEA',               'SEDEC – Centro Terapêutico TEA e Neuroatipias'),
    ('SEDEC_SUBGOP',              'SEDEC – Subsecretaria de Gestão Operacional'),
    ('SEDEC_ASSADM',              'SEDEC – Assessoria Administrativa'),
    ('SEDEC_SECEXEC',             'SEDEC – Secretário Executivo'),
    ('SEDEC_GABPRO',              'SEDEC – Gabinete de Projetos'),
    ('SEDEC_CPRODEC',             'SEDEC – Coord. Prog. Reforço Operacional DC'),
    ('SEDEC_SUOP',                'SEDEC – SUOP'),
    ('SEDEC_DGAC',                'SEDEC – DGAC'),
    ('SEDEC_CAML',                'SEDEC – Coord. de Apoio à Medicina Legal'),
    ('SEDEC_CPSADC',              'SEDEC – Centro de Proteção Socioambiental DC'),
    ('SEDEC_DGDEC',               'SEDEC – DGDEC'),
    ('SEDEC_DII',                 'SEDEC – Diretoria de Integração Interinstitucional'),
    ('SEDEC_DRDC',                'SEDEC – Diretoria das Regionais de DC'),
    ('SEDEC_CGREDEC',             'SEDEC – CGREDEC'),
    ('SEDEC_REDEC_1',             'SEDEC – REDEC 1 – Capital'),
    ('SEDEC_REDEC_2',             'SEDEC – REDEC 2 – Baixada Fluminense'),
    ('SEDEC_REDEC_3',             'SEDEC – REDEC 3 – Metropolitana'),
    ('SEDEC_REDEC_4',             'SEDEC – REDEC 4 – Costa Verde'),
    ('SEDEC_REDEC_5',             'SEDEC – REDEC 5 – Sul I'),
    ('SEDEC_REDEC_6',             'SEDEC – REDEC 6 – Sul II'),
    ('SEDEC_REDEC_7',             'SEDEC – REDEC 7 – Serrana I'),
    ('SEDEC_REDEC_8',             'SEDEC – REDEC 8 – Serrana II'),
    ('SEDEC_REDEC_9',             'SEDEC – REDEC 9 – Baixada Litorânea'),
    ('SEDEC_REDEC_10',            'SEDEC – REDEC 10 – Norte'),
    ('SEDEC_REDEC_11',            'SEDEC – REDEC 11 – Noroeste'),
    ('SEDEC_CEAACR_ANTIGO_CEAMA', 'SEDEC – CEAACR (ANTIGO CEAMA)'),
    ('SEDEC_CEDC_ENG',            'SEDEC – Coord. de Engenharia em DC'),
    ('SEDEC_CEMADEN',             'SEDEC – CEMADEN'),
    ('SEDEC_CESTAD',              'SEDEC – CESTAD'),
    ('SEDEC_CESTGEN',             'SEDEC – CESTGEN'),
    ('SEDEC_CCCEN',               'SEDEC – CCCEN'),
    ('SEDEC_ICTDEC',              'SEDEC – ICTDEC'),
    ('SEDEC_ESDEC',               'SEDEC – ESDEC'),
    ('SEDEC_CEPEDEC',             'SEDEC – CEPEDEC'),
    ('SEDEC_OUVIDORIAGERAL',      'SEDEC – OUVIDORIA-GERAL'),
    ('SEDEC_ASSINFO',             'SEDEC – ASSINFO'),
]

OBM_GROUPS = [
    ('CBMERJ', [
        # Comando-Geral
        ('CBMERJ_GCG',        'CBMERJ – Gabinete do Comando-Geral'),
        ('CBMERJ_CHGCG',      'CBMERJ – Chefia de Gabinete do CG'),
        ('CBMERJ_NUPROEISBM', 'CBMERJ – NUPROEISBM'),
        ('CBMERJ_FUNESBOM',   'CBMERJ – FUNESBOM'),
        ('CBMERJ_CI',         'CBMERJ – CI'),
        ('CBMERJ_GEP',        'CBMERJ – GEP'),
        ('CBMERJ_AJG',        'CBMERJ – AJG'),
        ('CBMERJ_SCP',        'CBMERJ – SCP'),
        ('CBMERJ_CHC',        'CBMERJ – CHC'),
        ('CBMERJ_MH',         'CBMERJ – Museu Histórico'),
        ('CBMERJ_GBMus',      'CBMERJ – GBMus'),
        ('CBMERJ_CHEMG',      'CBMERJ – CHEMG'),
        ('CBMERJ_SUBCHADM',   'CBMERJ – SUBCHADM'),
        ('CBMERJ_SUBCHOP',    'CBMERJ – SUBCHOP'),
        ('CBMERJ_SEMG',       'CBMERJ – Secretaria do EMG'),
        ('CBMERJ_GGPEMG',     'CBMERJ – Gab. de Gestão de Projetos do EMG'),
        ('CBMERJ_ASSPAR',     'CBMERJ – ASSPAR'),
        # Diretorias / Subcomando
        ('CBMERJ_GSCG',       'CBMERJ – Gabinete do Subcomando-Geral'),
        ('CBMERJ_BM/1',       'CBMERJ – BM/1'),
        ('CBMERJ_BM/4',       'CBMERJ – BM/4'),
        ('CBMERJ_BM/5',       'CBMERJ – BM/5'),
        ('CBMERJ_BM/2',       'CBMERJ – BM/2'),
        ('CBMERJ_BM/3',       'CBMERJ – BM/3'),
        ('CBMERJ_BM/6',       'CBMERJ – BM/6'),
        ('CBMERJ_BM/7',       'CBMERJ – BM/7'),
        ('CBMERJ_ASSEMG',     'CBMERJ – ASSEMG'),
        ('CBMERJ_DGCCO',      'CBMERJ – DGCCO'),
        ('CBMERJ_COCB',       'CBMERJ – Centro de Operações CB'),
        ('CBMERJ_COAPH',      'CBMERJ – Centro de Op. Atend. Pré-Hospitalar'),
        ('CBMERJ_DGP',        'CBMERJ – DGP'),
        ('CBMERJ_CPM',        'CBMERJ – CPM'),
        ('CBMERJ_DGST',       'CBMERJ – DGST'),
        ('CBMERJ_DPPT',       'CBMERJ – DPPT'),
        ('CBMERJ_DCST',       'CBMERJ – Diretoria de Controle de Serv. Técnicos'),
        ('CBMERJ_DGAL',       'CBMERJ – DGAL'),
        ('CBMERJ_CSM',        'CBMERJ – CSM'),
        ('CBMERJ_CSM/MMOTO',  'CBMERJ – CSM/MMOTO'),
        ('CBMERJ_CSM/MOP',    'CBMERJ – CSM/MOP'),
        ('CBMERJ_CSM/MTEL',   'CBMERJ – CSM/MTEL'),
        ('CBMERJ_ALGEBOM',    'CBMERJ – ALGEBOM'),
        ('CBMERJ_ALMED',      'CBMERJ – ALMED'),
        ('CBMERJ_ALOD',       'CBMERJ – ALOD'),
        ('CBMERJ_ALSE',       'CBMERJ – ALSE'),
        ('CBMERJ_DGF',        'CBMERJ – DGF'),
        ('CBMERJ_PAGCEN',     'CBMERJ – Pagadoria Central'),
        ('CBMERJ_DGEI',       'CBMERJ – DGEI'),
        ('CBMERJ_ESCBM',      'CBMERJ – ESCBM'),
        ('CBMERJ_ABMDPII',    'CBMERJ – ABMDPII'),
        ('CBMERJ_CFAP',       'CBMERJ – CFAP'),
        ('CBMERJ_CEICS',      'CBMERJ – CEICS'),
        ('CBMERJ_DBM/ESCOLA', 'CBMERJ – DBM/ESCOLA'),
        ('CBMERJ_CEFID',      'CBMERJ – CEFID'),
        ('CBMERJ_CTRM',       'CBMERJ – CTRM'),
        ('CBMERJ_DI',         'CBMERJ – DI'),
        ('CBMERJ_CIEB',       'CBMERJ – CIEB'),
        ('CBMERJ_DGVP',       'CBMERJ – DGVP'),
        ('CBMERJ_DGS',        'CBMERJ – DGS'),
        ('CBMERJ_PMEDQCG',    'CBMERJ – PMED-QCG'),
        ('CBMERJ_PMEDDGEI',   'CBMERJ – PMED-DGEI'),
        ('CBMERJ_PMEDCSM',    'CBMERJ – PMED-CSM'),
        ('CBMERJ_CGSI',       'CBMERJ – CGSI'),
        ('CBMERJ_DGAS',       'CBMERJ – DGAS'),
        ('CBMERJ_DGDP',       'CBMERJ – DGDP'),
        ('CBMERJ_DGPAT',      'CBMERJ – DGPAT'),
        ('CBMERJ_DGEAO',      'CBMERJ – DGEAO'),
        ('CBMERJ_DGSE',       'CBMERJ – DGSE'),
        # Saúde
        ('CBMERJ_HCAP',   'CBMERJ – HCAP'),
        ('CBMERJ_1_POL',  'CBMERJ – 1ª POL'),
        ('CBMERJ_2_POL',  'CBMERJ – 2ª POL'),
        ('CBMERJ_3_POL',  'CBMERJ – 3ª POL'),
        ('CBMERJ_4_POL',  'CBMERJ – 4ª POL'),
        ('CBMERJ_FARB',   'CBMERJ – FARB'),
        ('CBMERJ_1CTQ',   'CBMERJ – 1º CTQ – Campinho'),
        # Odontologia
        ('CBMERJ_DGO',             'CBMERJ – DGO'),
        ('CBMERJ_CEPO',            'CBMERJ – CEPO'),
        ('CBMERJ_CGOM',            'CBMERJ – Centro Gestor de Odontologia Móvel'),
        ('CBMERJ_CGUOD',           'CBMERJ – CGUOD'),
        ('CBMERJ_1_Odontoclnica',  'CBMERJ – 1ª Odontoclínica'),
        ('CBMERJ_2_Odontoclnica',  'CBMERJ – 2ª Odontoclínica'),
        ('CBMERJ_3_Odontoclnica',  'CBMERJ – 3ª Odontoclínica'),
        ('CBMERJ_4_Odontoclnica',  'CBMERJ – 4ª Odontoclínica'),
        ('CBMERJ_5_Odontoclnica',  'CBMERJ – 5ª Odontoclínica'),
        ('CBMERJ_6_Odontoclnica',  'CBMERJ – 6ª Odontoclínica'),
        ('CBMERJ_7_Odontoclnica',  'CBMERJ – 7ª Odontoclínica'),
        ('CBMERJ_8_Odontoclnica',  'CBMERJ – 8ª Odontoclínica'),
        ('CBMERJ_9_Odontoclnica',  'CBMERJ – 9ª Odontoclínica'),
        ('CBMERJ_10_Odontoclnica', 'CBMERJ – 10ª Odontoclínica'),
        ('CBMERJ_11_Odontoclnica', 'CBMERJ – 11ª Odontoclínica'),
        ('CBMERJ_CRODO_MET',  'CBMERJ – Coord. Regional Odonto. Metropolitana'),
        ('CBMERJ_CRODO_SERR', 'CBMERJ – Coord. Regional Odonto. Serrana'),
        ('CBMERJ_CRODO_SUL',  'CBMERJ – Coord. Regional Odonto. Sul'),
        ('CBMERJ_CRODO_NN',   'CBMERJ – Coord. Regional Odonto. Norte-Noroeste'),
        ('CBMERJ_CRODO_LIT',  'CBMERJ – Coord. Regional Odonto. Litorânea'),
        ('CBMERJ_CRODO_CV',   'CBMERJ – Coord. Regional Odonto. Costa Verde'),
    ]),
    ('CBMERJ/CBA I', [
        ('CBMERJ/CBA_I_CBA_I',       'CBMERJ/CBA I – CBA I'),
        ('CBMERJ/CBA_I_GOCG',        'CBMERJ/CBA I – GOCG'),
        ('CBMERJ/CBA_I_DBM_1/GOCG',  'CBMERJ/CBA I – DBM 1/GOCG'),
        ('CBMERJ/CBA_I_PABM_1/GOCG', 'CBMERJ/CBA I – PABM 1/GOCG'),
        ('CBMERJ/CBA_I_1_GBM',       'CBMERJ/CBA I – 1º GBM'),
        ('CBMERJ/CBA_I_DBM_1/1',     'CBMERJ/CBA I – DBM 1/1'),
        ('CBMERJ/CBA_I_2_GBM',       'CBMERJ/CBA I – 2º GBM'),
        ('CBMERJ/CBA_I_DBM_1/2',     'CBMERJ/CBA I – DBM 1/2'),
        ('CBMERJ/CBA_I_8_GBM',       'CBMERJ/CBA I – 8º GBM'),
        ('CBMERJ/CBA_I_11_GBM',      'CBMERJ/CBA I – 11º GBM'),
        ('CBMERJ/CBA_I_DBM_1/11',    'CBMERJ/CBA I – DBM 1/11'),
        ('CBMERJ/CBA_I_DBM_2/11',    'CBMERJ/CBA I – DBM 2/11'),
        ('CBMERJ/CBA_I_DBM_3/11',    'CBMERJ/CBA I – DBM 3/11'),
        ('CBMERJ/CBA_I_12_GBM',      'CBMERJ/CBA I – 12º GBM'),
        ('CBMERJ/CBA_I_13_GBM',      'CBMERJ/CBA I – 13º GBM'),
        ('CBMERJ/CBA_I_DBM_1/13',    'CBMERJ/CBA I – DBM 1/13'),
        ('CBMERJ/CBA_I_DBM_2/13',    'CBMERJ/CBA I – DBM 2/13'),
        ('CBMERJ/CBA_I_17_GBM',      'CBMERJ/CBA I – 17º GBM'),
        ('CBMERJ/CBA_I_19_GBM',      'CBMERJ/CBA I – 19º GBM'),
        ('CBMERJ/CBA_I_DBM_1/19',    'CBMERJ/CBA I – DBM 1/19'),
        ('CBMERJ/CBA_I_24_GBM',      'CBMERJ/CBA I – 24º GBM'),
        ('CBMERJ/CBA_I_DBM_1/24',    'CBMERJ/CBA I – DBM 1/24'),
        ('CBMERJ/CBA_I_DBM_2/24',    'CBMERJ/CBA I – DBM 2/24'),
        ('CBMERJ/CBA_I_DBM_3/24',    'CBMERJ/CBA I – DBM 3/24'),
        ('CBMERJ/CBA_I_25_GBM',      'CBMERJ/CBA I – 25º GBM'),
        ('CBMERJ/CBA_I_28_GBM',      'CBMERJ/CBA I – 28º GBM'),
        ('CBMERJ/CBA_I_30_GBM',      'CBMERJ/CBA I – 30º GBM'),
    ]),
    ('CBMERJ/CBA II', [
        ('CBMERJ/CBA_II_CBA_II',    'CBMERJ/CBA II – CBA II'),
        ('CBMERJ/CBA_II_6_GBM',     'CBMERJ/CBA II – 6º GBM'),
        ('CBMERJ/CBA_II_DBM_1/6',   'CBMERJ/CBA II – DBM 1/6'),
        ('CBMERJ/CBA_II_DBM_2/6',   'CBMERJ/CBA II – DBM 2/6'),
        ('CBMERJ/CBA_II_DBM_3/6',   'CBMERJ/CBA II – DBM 3/6'),
        ('CBMERJ/CBA_II_DBM_4/6',   'CBMERJ/CBA II – DBM 4/6'),
        ('CBMERJ/CBA_II_PABM_1/6',  'CBMERJ/CBA II – PABM 1/6'),
        ('CBMERJ/CBA_II_15_GBM',    'CBMERJ/CBA II – 15º GBM'),
        ('CBMERJ/CBA_II_DBM_1/15',  'CBMERJ/CBA II – DBM 1/15'),
        ('CBMERJ/CBA_II_DBM_2/15',  'CBMERJ/CBA II – DBM 2/15'),
        ('CBMERJ/CBA_II_DBM_3/15',  'CBMERJ/CBA II – DBM 3/15'),
        ('CBMERJ/CBA_II_16_GBM',    'CBMERJ/CBA II – 16º GBM'),
        ('CBMERJ/CBA_II_DBM_1/16',  'CBMERJ/CBA II – DBM 1/16'),
        ('CBMERJ/CBA_II_DBM_2/16',  'CBMERJ/CBA II – DBM 2/16'),
    ]),
    ('CBMERJ/CBA III', [
        ('CBMERJ/CBA_III_CBA_III',   'CBMERJ/CBA III – CBA III'),
        ('CBMERJ/CBA_III_7_GBM',     'CBMERJ/CBA III – 7º GBM'),
        ('CBMERJ/CBA_III_22_GBM',    'CBMERJ/CBA III – 22º GBM'),
        ('CBMERJ/CBA_III_DBM_1/22',  'CBMERJ/CBA III – DBM 1/22'),
        ('CBMERJ/CBA_III_DBM_2/22',  'CBMERJ/CBA III – DBM 2/22'),
        ('CBMERJ/CBA_III_DBM_3/22',  'CBMERJ/CBA III – DBM 3/22'),
        ('CBMERJ/CBA_III_23_GBM',    'CBMERJ/CBA III – 23º GBM'),
        ('CBMERJ/CBA_III_DBM_1/23',  'CBMERJ/CBA III – DBM 1/23'),
        ('CBMERJ/CBA_III_29_GBM',    'CBMERJ/CBA III – 29º GBM'),
        ('CBMERJ/CBA_III_DBM_1/29',  'CBMERJ/CBA III – DBM 1/29'),
        ('CBMERJ/CBA_III_DBM_2/29',  'CBMERJ/CBA III – DBM 2/29'),
        ('CBMERJ/CBA_III_DBM_3/29',  'CBMERJ/CBA III – DBM 3/29'),
        ('CBMERJ/CBA_III_DBM_4/29',  'CBMERJ/CBA III – DBM 4/29'),
    ]),
    ('CBMERJ/CBA IV', [
        ('CBMERJ/CBA_IV_CBA_IV',    'CBMERJ/CBA IV – CBA IV'),
        ('CBMERJ/CBA_IV_CRM/MMOTO', 'CBMERJ/CBA IV – CRM/MMOTO'),
        ('CBMERJ/CBA_IV_5_GBM',     'CBMERJ/CBA IV – 5º GBM'),
        ('CBMERJ/CBA_IV_DBM_1/5',   'CBMERJ/CBA IV – DBM 1/5'),
        ('CBMERJ/CBA_IV_DBM_2/5',   'CBMERJ/CBA IV – DBM 2/5'),
        ('CBMERJ/CBA_IV_DBM_3/5',   'CBMERJ/CBA IV – DBM 3/5'),
        ('CBMERJ/CBA_IV_DBM_4/5',   'CBMERJ/CBA IV – DBM 4/5'),
        ('CBMERJ/CBA_IV_DBM_5/5',   'CBMERJ/CBA IV – DBM 5/5'),
        ('CBMERJ/CBA_IV_DBM_6/5',   'CBMERJ/CBA IV – DBM 6/5'),
        ('CBMERJ/CBA_IV_21_GBM',    'CBMERJ/CBA IV – 21º GBM'),
        ('CBMERJ/CBA_IV_DBM_1/21',  'CBMERJ/CBA IV – DBM 1/21'),
        ('CBMERJ/CBA_IV_DBM_2/21',  'CBMERJ/CBA IV – DBM 2/21'),
        ('CBMERJ/CBA_IV_DBM_3/21',  'CBMERJ/CBA IV – DBM 3/21'),
        ('CBMERJ/CBA_IV_DBM_4/21',  'CBMERJ/CBA IV – DBM 4/21'),
        ('CBMERJ/CBA_IV_DBM_5/21',  'CBMERJ/CBA IV – DBM 5/21'),
        ('CBMERJ/CBA_IV_DBM_6/21',  'CBMERJ/CBA IV – DBM 6/21'),
    ]),
    ('CBMERJ/CBA V', [
        ('CBMERJ/CBA_V_CBA_V',     'CBMERJ/CBA V – CBA V'),
        ('CBMERJ/CBA_V_9_GBM',     'CBMERJ/CBA V – 9º GBM'),
        ('CBMERJ/CBA_V_DBM_1/9',   'CBMERJ/CBA V – DBM 1/9'),
        ('CBMERJ/CBA_V_DBM_2/9',   'CBMERJ/CBA V – DBM 2/9'),
        ('CBMERJ/CBA_V_PABM_1/9',  'CBMERJ/CBA V – PABM 1/9'),
        ('CBMERJ/CBA_V_18_GBM',    'CBMERJ/CBA V – 18º GBM'),
        ('CBMERJ/CBA_V_DBM_1/18',  'CBMERJ/CBA V – DBM 1/18'),
        ('CBMERJ/CBA_V_DBM_2/18',  'CBMERJ/CBA V – DBM 2/18'),
        ('CBMERJ/CBA_V_PABM_1/18', 'CBMERJ/CBA V – PABM 1/18'),
        ('CBMERJ/CBA_V_27_GBM',    'CBMERJ/CBA V – 27º GBM'),
        ('CBMERJ/CBA_V_DBM_1/27',  'CBMERJ/CBA V – DBM 1/27'),
        ('CBMERJ/CBA_V_DBM_2/27',  'CBMERJ/CBA V – DBM 2/27'),
    ]),
    ('CBMERJ/CBA VI', [
        ('CBMERJ/CBA_VI_CBA_VI',   'CBMERJ/CBA VI – CBA VI'),
        ('CBMERJ/CBA_VI_4_GBM',    'CBMERJ/CBA VI – 4º GBM'),
        ('CBMERJ/CBA_VI_DBM_1/4',  'CBMERJ/CBA VI – DBM 1/4'),
        ('CBMERJ/CBA_VI_DBM_2/4',  'CBMERJ/CBA VI – DBM 2/4'),
        ('CBMERJ/CBA_VI_DBM_3/4',  'CBMERJ/CBA VI – DBM 3/4'),
        ('CBMERJ/CBA_VI_DBM_4/4',  'CBMERJ/CBA VI – DBM 4/4'),
        ('CBMERJ/CBA_VI_14_GBM',   'CBMERJ/CBA VI – 14º GBM'),
        ('CBMERJ/CBA_VI_DBM_1/14', 'CBMERJ/CBA VI – DBM 1/14'),
    ]),
    ('CBMERJ/CBA VII', [
        ('CBMERJ/CBA_VII_CBA_VII',   'CBMERJ/CBA VII – CBA VII'),
        ('CBMERJ/CBA_VII_10_GBM',    'CBMERJ/CBA VII – 10º GBM'),
        ('CBMERJ/CBA_VII_DBM_1/10',  'CBMERJ/CBA VII – DBM 1/10'),
        ('CBMERJ/CBA_VII_DBM_2/10',  'CBMERJ/CBA VII – DBM 2/10'),
        ('CBMERJ/CBA_VII_DBM_3/10',  'CBMERJ/CBA VII – DBM 3/10'),
        ('CBMERJ/CBA_VII_DBM_4/10',  'CBMERJ/CBA VII – DBM 4/10'),
        ('CBMERJ/CBA_VII_26_GBM',    'CBMERJ/CBA VII – 26º GBM'),
        ('CBMERJ/CBA_VII_DBM_1/26',  'CBMERJ/CBA VII – DBM 1/26'),
    ]),
    ('CBMERJ/CBA VIII', [
        ('CBMERJ/CBA_VIII_CBA_VIII',  'CBMERJ/CBA VIII – CBA VIII'),
        ('CBMERJ/CBA_VIII_GBS',       'CBMERJ/CBA VIII – GBS'),
        ('CBMERJ/CBA_VIII_DBM_1/GBS', 'CBMERJ/CBA VIII – DBM 1/GBS'),
        ('CBMERJ/CBA_VIII_PABM_1/GBS','CBMERJ/CBA VIII – PABM 1/GBS'),
        ('CBMERJ/CBA_VIII_1_GSFMA',   'CBMERJ/CBA VIII – 1º GSFMA'),
        ('CBMERJ/CBA_VIII_2_GSFMA',   'CBMERJ/CBA VIII – 2º GSFMA'),
        ('CBMERJ/CBA_VIII_GTSAI',     'CBMERJ/CBA VIII – GTSAI'),
        ('CBMERJ/CBA_VIII_GOA',       'CBMERJ/CBA VIII – GOA'),
        ('CBMERJ/CBA_VIII_DBM_1/GOA', 'CBMERJ/CBA VIII – DBM 1/GOA'),
        ('CBMERJ/CBA_VIII_COVANT',    'CBMERJ/CBA VIII – COVANT'),
        ('CBMERJ/CBA_VIII_GOPP',      'CBMERJ/CBA VIII – GOPP'),
        ('CBMERJ/CBA_VIII_DBM/MOTO',  'CBMERJ/CBA VIII – DBM/MOTO'),
        ('CBMERJ/CBA_VIII_GBRESC',    'CBMERJ/CBA VIII – GBRESC'),
        ('CBMERJ/CBA_VIII_GSE',       'CBMERJ/CBA VIII – Gp. de Socorro de Emergência'),
    ]),
    ('CBMERJ/CBA IX', [
        ('CBMERJ/CBA_IX_CBA_IX',    'CBMERJ/CBA IX – CBA IX'),
        ('CBMERJ/CBA_IX_3_GBM',     'CBMERJ/CBA IX – 3º GBM'),
        ('CBMERJ/CBA_IX_DBM_1/3',   'CBMERJ/CBA IX – DBM 1/3'),
        ('CBMERJ/CBA_IX_DBM_2/3',   'CBMERJ/CBA IX – DBM 2/3'),
        ('CBMERJ/CBA_IX_20_GBM',    'CBMERJ/CBA IX – 20º GBM'),
        ('CBMERJ/CBA_IX_DBM_1/20',  'CBMERJ/CBA IX – DBM 1/20'),
        ('CBMERJ/CBA_IX_DBM_2/20',  'CBMERJ/CBA IX – DBM 2/20'),
        ('CBMERJ/CBA_IX_DBM_3/20',  'CBMERJ/CBA IX – DBM 3/20'),
    ]),
    ('CBMERJ/CBA X', [
        ('CBMERJ/CBA_X_CBA_X',   'CBMERJ/CBA X – CBA X'),
        ('CBMERJ/CBA_X_CER',     'CBMERJ/CBA X – CER'),
        ('CBMERJ/CBA_X_1_GMAR',  'CBMERJ/CBA X – 1º GMAR'),
        ('CBMERJ/CBA_X_DBM_1/M', 'CBMERJ/CBA X – DBM 1/M'),
        ('CBMERJ/CBA_X_DBM_2/M', 'CBMERJ/CBA X – DBM 2/M'),
        ('CBMERJ/CBA_X_2_GMAR',  'CBMERJ/CBA X – 2º GMAR'),
        ('CBMERJ/CBA_X_DBM_3/M', 'CBMERJ/CBA X – DBM 3/M'),
        ('CBMERJ/CBA_X_DBM_4/M', 'CBMERJ/CBA X – DBM 4/M'),
        ('CBMERJ/CBA_X_DBM_5/M', 'CBMERJ/CBA X – DBM 5/M'),
        ('CBMERJ/CBA_X_3_GMAR',  'CBMERJ/CBA X – 3º GMAR'),
        ('CBMERJ/CBA_X_4_GMAR',  'CBMERJ/CBA X – 4º GMAR'),
        ('CBMERJ/CBA_X_DBM_6/M', 'CBMERJ/CBA X – DBM 6/M'),
    ]),
    ('SEDEC', [
        ('SEDEC_GABSEC',              'SEDEC – Gabinete do Secretário'),
        ('SEDEC_CH_GAB_SEDEC',        'SEDEC – CH GAB SEDEC'),
        ('SEDEC_ASESP',               'SEDEC – Assessoria Especial'),
        ('SEDEC_ASSEJUR',             'SEDEC – ASSEJUR'),
        ('SEDEC_ASSPLO',              'SEDEC – ASSPLO'),
        ('SEDEC_ACS',                 'SEDEC – ACS'),
        ('SEDEC_ARINT',               'SEDEC – Assessoria de Relações Internacionais'),
        ('SEDEC_ARINST',              'SEDEC – ARINST'),
        ('SEDEC_ARGOV',               'SEDEC – Assessoria de Relações Governamentais'),
        ('SEDEC_CPARJ',               'SEDEC – Coord. Parlamentar no RJ'),
        ('SEDEC_CPABSB',              'SEDEC – Coord. Parlamentar em Brasília'),
        ('SEDEC_CAL',                 'SEDEC – Coord. de Assuntos Legislativos'),
        ('SEDEC_CONTROLADORIA_SEDEC', 'SEDEC – CONTROLADORIA SEDEC'),
        ('SEDEC_CORREGEDORIA',        'SEDEC – Corregedoria-Geral'),
        ('SEDEC_CRD',                 'SEDEC – CRD'),
        ('SEDEC_OUVIDORIAGERAL',      'SEDEC – OUVIDORIA-GERAL'),
        ('SEDEC_SUBSEDEC',            'SEDEC – SUBSEDEC'),
        ('SEDEC_SUBGAD',              'SEDEC – Subsecretaria de Gestão Administrativa'),
        ('SEDEC_CRVD_SALA_LILAS',     'SEDEC – CRVD (SALA LILAS)'),
        ('SEDEC_SUAD',                'SEDEC – SUAD'),
        ('SEDEC_DGAF',                'SEDEC – DGAF'),
        ('SEDEC_ASSINFO',             'SEDEC – ASSINFO'),
        ('SEDEC_DGTI',                'SEDEC – DG de Tecnologia da Informação'),
        ('SEDEC_DGBP',                'SEDEC – DG de Bens Patrimoniais'),
        ('SEDEC_DPSEDEC',             'SEDEC – Diretoria de Patrimônio da SEDEC'),
        ('SEDEC_DPCBMERJ',            'SEDEC – Diretoria de Patrimônio do CBMERJ'),
        ('SEDEC_DGI',                 'SEDEC – DG de Intendência'),
        ('SEDEC_CTAPL',               'SEDEC – Centro de Apoio Logístico'),
        ('SEDEC_SUSAU',               'SEDEC – SUSAU'),
        ('SEDEC_CTTEA',               'SEDEC – Centro Terapêutico TEA e Neuroatipias'),
        ('SEDEC_SUBGOP',              'SEDEC – Subsecretaria de Gestão Operacional'),
        ('SEDEC_ASSADM',              'SEDEC – Assessoria Administrativa'),
        ('SEDEC_SECEXEC',             'SEDEC – Secretário Executivo'),
        ('SEDEC_GABPRO',              'SEDEC – Gabinete de Projetos'),
        ('SEDEC_CPRODEC',             'SEDEC – Coord. Prog. Reforço Operacional DC'),
        ('SEDEC_SUOP',                'SEDEC – SUOP'),
        ('SEDEC_DGAC',                'SEDEC – DGAC'),
        ('SEDEC_CAML',                'SEDEC – Coord. de Apoio à Medicina Legal'),
        ('SEDEC_CPSADC',              'SEDEC – Centro de Proteção Socioambiental DC'),
        ('SEDEC_DGDEC',               'SEDEC – DGDEC'),
        ('SEDEC_DII',                 'SEDEC – Diretoria de Integração Interinstitucional'),
        ('SEDEC_DRDC',                'SEDEC – Diretoria das Regionais de DC'),
        ('SEDEC_CGREDEC',             'SEDEC – CGREDEC'),
        ('SEDEC_REDEC_1',             'SEDEC – REDEC 1 – Capital'),
        ('SEDEC_REDEC_2',             'SEDEC – REDEC 2 – Baixada Fluminense'),
        ('SEDEC_REDEC_3',             'SEDEC – REDEC 3 – Metropolitana'),
        ('SEDEC_REDEC_4',             'SEDEC – REDEC 4 – Costa Verde'),
        ('SEDEC_REDEC_5',             'SEDEC – REDEC 5 – Sul I'),
        ('SEDEC_REDEC_6',             'SEDEC – REDEC 6 – Sul II'),
        ('SEDEC_REDEC_7',             'SEDEC – REDEC 7 – Serrana I'),
        ('SEDEC_REDEC_8',             'SEDEC – REDEC 8 – Serrana II'),
        ('SEDEC_REDEC_9',             'SEDEC – REDEC 9 – Baixada Litorânea'),
        ('SEDEC_REDEC_10',            'SEDEC – REDEC 10 – Norte'),
        ('SEDEC_REDEC_11',            'SEDEC – REDEC 11 – Noroeste'),
        ('SEDEC_CEAACR_ANTIGO_CEAMA', 'SEDEC – CEAACR (ANTIGO CEAMA)'),
        ('SEDEC_CEDC_ENG',            'SEDEC – Coord. de Engenharia em DC'),
        ('SEDEC_CEMADEN',             'SEDEC – CEMADEN'),
        ('SEDEC_CESTAD',              'SEDEC – CESTAD'),
        ('SEDEC_CESTGEN',             'SEDEC – CESTGEN'),
        ('SEDEC_CCCEN',               'SEDEC – CCCEN'),
        ('SEDEC_ICTDEC',              'SEDEC – ICTDEC'),
        ('SEDEC_ESDEC',               'SEDEC – ESDEC'),
        ('SEDEC_CEPEDEC',             'SEDEC – CEPEDEC'),
    ]),
]
